Update license_file to license_files
dpkp/kafka-python pull request #2415
Opened 2023-11-18 01:05 UTC by micwoj92

The former has been deprecated since setuptools 56

2023-11-25 03:07 UTC, 50-Course requested changes
Hello,

Thank you for making this patch. I think it would be best if old diff is maintained since, at the moment, `kafka-python` package is not using multiple Licenses.

2023-11-25 04:23 UTC, micwoj92 commented
It does not matter.
https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#metadata

2023-12-14 02:11 UTC, wbarnha commented
We'll merge this in after the next release.

2023-12-14 02:11 UTC, wbarnha approved these changes

2025-02-07 01:35 UTC, dpkp commented
Rebased: #2462

2025-02-07 01:35 UTC, closed without merging